### ISSUE TITLE
Can't install matplotlib since the dependency distutils is missing

### ISSUE THREAD

**Issue by voldemarz** [Matthew1471/Bosch-EasyControl-Utilities#1]
matplotlib failed to install complaining about missing distutils

Turn out [distutils](https://docs.python.org/3/library/distutils.html#module-distutils) is deprecated and removed since Python 3.12. See the [What’s New](https://docs.python.org/3/whatsnew/3.10.html#distutils-deprecated) entry for more information.

**Comment by voldemarz** [comment]
Maybe you can share the mentioned Weather Compensation Guide? Not finding anything like that online.
DM me on twitter https://twitter.com/voldemarz

**Comment by Matthew1471** [comment]
It looks like "matplotlib" no longer requires distutils as of 3.6.0 (Sep 16, 2022)? : https://github.com/matplotlib/matplotlib/issues/21643 and https://github.com/matplotlib/matplotlib/issues/21057 . Might it be that you already had it installed but it fails because of the missing library import? Try a pip upgrade (`pip install matplotlib --upgrade`) the latest is 3.8.2.

I am not sure if I can share the PDF in the repo as it isn't mine to share (and likely copyright), but to get it I just e-mailed technical-advice@uk.bosch.com and asked for the EasyControl WDC Guide / Settings and they sent it - so they should be able to send it to you with no hassle too. The filename is "Bosch EasyControl - Weather Compensation Guide - v5.pdf" (but the footer says v4)

I've also updated this project to work with newer versions of matplotlib.

**Comment by voldemarz** [comment]
I got it to run.. Don't recall how resolved diskutils issue, but got to the point where matplotlib install was failing cause it was trying build it. Didn't want to install Visual Studio and dig into how it works with Python and avoid any potential conflict with other Python installation. Found that Anaconda \ Conda provides pre-built versions, so ended up running it that way. 

Would have helped if there were a little bit more pointers in documentation regarding Python. Also would be good to specify that need to pass a zip file to Display_Settings either in docs or py script.
